meine/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, RadioField
from wtforms.validators import data_required, EqualTo
from meine.models import Board


def board_list():
    default = (0, 'Nic nie usuwaj')
    choice = [default]
    for board in Board.query.all():
        choice.append((board.id, board.name))

    return choice


class LoginForm(FlaskForm):

    name = StringField('Podaj Login', validators=[data_required()])
    password = PasswordField('Podaj Hasło', validators=[data_required()])
    submit = SubmitField('Potwierdz')

class AdminControlForm(FlaskForm):
    submit = SubmitField('Zapisz zmiany')

class BoardForm(FlaskForm):
    name = StringField('Nazwa Tablicy', validators=[data_required()])
    info = TextAreaField('Opis Tablicy')
    submit = SubmitField('Dodaj Tablicę')

class DelBoardForm(FlaskForm):
    menu = RadioField('Tablica do usunięcia')
    submit = SubmitField('Usuń !!!')

class DelPost(FlaskForm):
    submit = SubmitField('TAK')

class ChangePass(FlaskForm):
    old_pass = PasswordField('Podaj swoje stare hasło', validators=[data_required()])
    new_pass = PasswordField('Podaj nowe hasło', validators=[data_required()])
    confirm_pass = PasswordField('Powtórz nowe hasło', validators=[data_required(), EqualTo('new_pass', message='Pola z nowym hasłem muszą być takie same')])
    submit = SubmitField('ZMIEŃ')

meine/users/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, flash
from meine.users.forms import LoginForm, BoardForm, DelPost, ChangePass
from meine.models import Users, Board, db, Posts
from flask_login import login_user, login_required, logout_user, current_user

users_blueprint = Blueprint('users', __name__, template_folder='templates')

def edit_comment(post, new_content):
    if post.date_edit == None:
        post.edit_date = post.set_edit_date()
        db.session.add(post)
        db.session.commit()

    signature = f"\n\n\nPost edytowany: {post.show_edit_date()} przez {current_user.name}"
    post.content = str(new_content) + str(signature)
    db.session.add(post)
    db.session.commit()

def board_list():
    default = (0, 'Nic nie usuwaj')
    choice = [default]
    for board in Board.query.all():
        choice.append((board.id, board.name))

    return choice

@users_blueprint.route('/', methods=['POST', 'GET'])
def home():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(name=form.name.data).first()
        if not user:
            flash('Nie ma takiego użytkownika')
        else:
            if user.check_password(form.password.data):
                login_user(user)
                return redirect(url_for('home'))
            else:
                flash('Złe hasło')



    return render_template('users/home.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

@users_blueprint.route('/admin')
@login_required
def admin():
    if current_user.role > 1:
        return redirect(url_for('home'))

    return render_template('users/admin.html')

@users_blueprint.route('/admin/board', methods=['POST', 'GET'])
@login_required
def add_board():
    form = BoardForm()
    if form.validate_on_submit():
        new_board = Board(name=form.name.data, info=form.info.data)
        db.session.add(new_board)
        db.session.commit()

        return redirect(url_for('chan.home'))

    return render_template('users/add_board.html', form=form)

@users_blueprint.route('/admin/delete', methods=['POST', 'GET'])
@login_required
def del_board():
    boards = Board.query.all()

    if request.method == 'POST':
        if request.form['boardRadio'] == '0':
            return redirect(url_for('users.admin'))
        deleted = Board.query.get(request.form['boardRadio'])
        db.session.delete(deleted)
        db.session.commit()

        return redirect(url_for('users.del_board'))



    return render_template('users/del_board.html', boards=boards)


@users_blueprint.route('/edit/<id>', methods=['POST', 'GET'])
@login_required
def edit_post(id):
    edited = Posts.query.get(id)
    if request.method == 'POST':
        new = request.form['editedPost']
        edit_comment(edited, new)

        return redirect(url_for('chan.board', id=edited.board_id))



    return render_template('users/edit_post.html', edited=edited)

@users_blueprint.route('/del/<id>', methods=['POST', 'GET'])
@login_required
def del_post(id):
    deleted = Posts.query.get(id)
    del_post = DelPost()
    if del_post.validate_on_submit():
        db.session.delete(deleted)
        db.session.commit()
        return redirect(url_for('chan.board', id=deleted.board_id))
    return render_template('users/del_post.html', deleted=deleted, form=del_post)

@users_blueprint.route('admin/account', methods=['POST', 'GET'])
@login_required
def change_pass():
    form = ChangePass()
    c_user = Users.query.get(current_user.id)

    if form.validate_on_submit():
        if not c_user.check_password(form.old_pass.data):
            flash('Stare hasło jest niepoprawne')
        else:

            print(form.confirm_pass.errors)
            c_user.set_password(form.confirm_pass.data)
            db.session.add(c_user)
            db.session.commit()
            flash('Ustawiono nowe hasło')


    return render_template('users/change_pass.html', form=form)

@users_blueprint.route('admin/move/<id>', methods=['POST', 'GET'])
@login_required
def move_post(id):
    moved = Posts.query.get(id)
    boards = Board.query.all()
    if request.method == 'POST':
        if request.form['boardRadio'] == '0':
            return redirect(url_for('chan.board', id=moved.board_id))
        target = Board.query.get(request.form['boardRadio'])
        moved.board_id = target.id
        db.session.add(moved)
        db.session.commit()
        flash('Post został przeniesiony')
        return redirect(url_for('chan.board', id=moved.board_id))

    return render_template('users/move_post.html', moved=moved, boards=boards)

meine/users/templates/users/add_board.html
{% extends "base.html" %}

{% block content %}


    <div class="container my-2 border border-secondary">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <div class="row my-2">
                <div class="col-md-6 col-12 text-center">
                    {{ form.name.label(class="form-control bg-warning bg-opacity-50") }}
                </div>
                <div class="col-md-6 col-12 text-center">
                    {{ form.name(class="form-control") }}
                </div>
            </div>

            <div class="row my-1">
                <div class="col-md-6 col-12 text-center">
                    {{ form.info.label(class="form-control bg-warning bg-opacity-50") }}
                </div>
                
                <div class="col-md-6 col-12 text-center">
                    {{ form.info(class="form-control") }}
                </div>
            </div>

            <div class="row my-2">
                <div class="col-md-6">
                    {{ form.submit(class="btn btn-success w-100 text-center") }}
                </div>
            </div>
        </form>





    </div>



    
{% endblock %}

meine/users/templates/users/admin.html
{% extends "base.html" %}

{% block content %}


  <div class="container my-2 bg-white bg-opacity-50 border border-secondary main-width">


    <div class="row text-center border-end border-dark">
      <p class="fw-bold fs-5"> Zarządzanie Tablicami </p>

    </div>

    <div class="row border-bottom border-end border-dark">
      <div class="col-md-6 col-12 text-center pb-2">
        <a href="{{ url_for('users.add_board') }}" class="btn btn-primary"> Dodaj Nową Tablicę </a>
      </div>

      <div class="col-md-6 col-12 text-center pb-2">
        <a href="{{ url_for('users.del_board') }}" class="btn btn-danger"> Usuń Tablicę </a>
      </div>

    </div>




  </div>

  <div class="container my-2 bg-white bg-opacity-50 border border-secondary main-width">

    <div class="row text-center border-end border-dark">
      <p class="fw-bold fs-5"> Zarządzanie Kontem </p>

    </div>
    <div class="row border-bottom border-end border-dark">
      <div class="col-md-6 col-12 text-center pb-2">
        <a href="{{ url_for('users.change_pass') }}" class="btn btn-primary"> Zmień hasło </a>
      </div>
  </div>


  

{% endblock %}

meine/users/templates/users/change_pass.html
{% extends "base.html" %}

{% block content %}

	<div class="container my-3 bg-white bg-opacity-50 main-width">
		<form action="" method="POST">
			{{ form.hidden_tag() }}
			<div class="container my-2">
				<div class="col-md6 col-12 my-1">
					{{ form.old_pass.label(class="form-label")}}
				</div>
				<div class="col-md6 col-12 my-1">
					{{ form.old_pass(class="form-control") }}
				</div>
			</div>

			<div class="container my-2">
				<div class="col-md6 col-12 my-1">
					{{ form.new_pass.label(class="form-label") }}
				</div>
				<div class="col-md6 col-12 my-1">
					{{ form.new_pass(class="form-control") }}
				</div>
			</div>

			<div class="container my-2">
				<div class="col-md6 col-12 my-1">
					{{ form.confirm_pass.label(class="form-label") }}
				</div>
				<div class="col-md6 col-12 my-1">
					{{ form.confirm_pass(class="form-control") }}
				</div>
			</div>

			<div class="container my-2">
				<div class="row d-flex justify-content-center">
					{{ form.submit(class="btn btn-danger", style="width: 250px;") }}
				</div>
			</div>


		</form>

		{% for error in form.confirm_pass.errors %}
			<div class="alert alert-danger">
				{{ error }}
			</div>
		{% endfor %}

		{% with messages = get_flashed_messages() %}

			{% if messages %}
				<div class="container my-2">
					{% for msg in messages %}
						<div class="alert alert-danger">
							{{ msg }}
						</div>
					{% endfor %}
				</div>
			{% endif %}

		{% endwith %}
	</div>

{% endblock %}

meine/users/templates/users/del_board.html
{% extends "base.html" %}
{% from "_macros.html" import radio_Board %}

{% block content %}



	<div class="container my-2">


		<div class="row text-center bg-danger bg-opacity-25">
			<h2> Wybierz Tablicę do usunięcia </h2>
		</div>



		<form action="" method="POST">
		
			{{ radio_Board(boards, "Nic nie usuwaj") }}

			<div class="row my-3">
				<input class="btn btn-danger" type="submit" value="USUŃ !!!">
			</div>
			
		</form>
	</div>



{% endblock %}

meine/users/templates/users/del_post.html
{% extends "base.html" %}

{% block content %}


	<div class="container my-3 bg-danger">
		<div class="row text-center">
			<p class="fst-1"> Czy napewno usunąć tego Posta ??? </p>
		</div>

		<div class="row">
			<div class="col-md-6 col-12 my-3 text-center">
				<a href="{{ url_for('chan.board', id=deleted.board_id)}}" class="btn btn-success"> NIE / Confij </a>
			</div>
			<div class="col-md-6 col-12 my-3 text-center"> 
				<form action="" method="POST">
					{{ form.hidden_tag() }}
					{{ form.submit(class="btn btn-dark", style="width: 100px;") }}
				</form>
			</div>
			
		</div>
	</div>




{% endblock %}

meine/users/templates/users/edit_post.html
{% extends "base.html" %}

{% block content %}

	<div class="container my-3" style="max-width: 1000px;">
		<form action="" method="POST">
			<div class="row my-1 text-center">
				<p class="fs-3"> Edytuj Post </p>
			</div>
			<div class="row my-1 text-center d-flex">
				<div class="col-md-8">
					<div class="mb-3">
						<textarea class="form-control" name="editedPost" rows="8" style="white-space: pre-line;"> {{ edited.content }} </textarea>
					</div>
				</div>
			</div>

			<div class="row my-1">
				<div class="col-md-6 col-12 bg-warning bg-opacity-50 text-center my-1">
					<a href="{{ url_for('chan.board', id=edited.board_id) }}" class="btn btn-dark"> Nie Edytuj / COFNIJ </a>
				</div>
				<div class="col-md-6 col-12 bg-warning bg-opacity-50 text-center my-1">
					<input class="btn btn-dark" type="submit" value="Edytuj" style="width:120px;"> 
				</div>
			</div>
		</form>
	</div>



{% endblock %}

meine/users/templates/users/home.html
{% extends "base.html" %}

{% block content %}


	<div class="container">

		{% with messages = get_flashed_messages() %}

			{% if messages %}

				{% for msg in messages %}

					<div class="alert alert-danger" role="alert">
						<p class="text-center"> {{ msg }} </p>
					</div>

				{% endfor %}

			{% endif %}

		{% endwith %}



		<form action="" method="POST">

			{{ form.hidden_tag() }}
			<div class="row my-1">
				<div class="col-md-6 text-center bg-white">
					<h4> {{ form.name.label(class="form-label") }} </h4>
				</div>

				<div class="col-md-6 text-center">
					{{ form.name(class="form-control") }}
				</div>
			</div>

			<div class="row my-1">
				<div class="col-md-6 text-center bg-white">
					<h5> {{ form.password.label(class="form-label") }} </h5>
				</div>

				<div class="col-md-6 text-center">
					{{ form.password(class="form-control") }}
				</div>
			</div>
			<div class="row my-1">
				{{ form.submit(class="btn btn-success") }}
			</div>
		</form>
	</div>



{% endblock %}

meine/users/templates/users/move_post.html
{% extends "base.html" %}
{% from "_macros.html" import radio_Board %}

{% block content %}

	<div class="container my-3 bg-white bg-opacity-50 main-width">
		<div class="row text-center">
			<h3> Wybierz Tablicę do której chcesz przenieść Posta </h3>
		</div>

		{% with messages = get_flashed_messages() %}

			{% if messages %}
				<div class="container my-2">
					{% for msg in messages %}
						<div class="alert alert-warning">
							{{ msg }}
						</div>
					{% endfor %}
				</div>
			{% endif %}

		{% endwith %}


		<form action="" method="POST">
		
			{{ radio_Board(boards, 'NIE PRZENOŚ') }}

			<div class="row my-3">
				<input class="btn btn-warning" type="submit" value="Przenieś">
			</div>
			
		</form>

		
	</div>

{% endblock %}