meine/chan/views.py
from flask import Blueprint, render_template, redirect, url_for
from meine.models import Board, Posts, db
from meine.chan.forms import PostForm
from flask_login import current_user

chan_blueprint = Blueprint('chan', __name__, template_folder='templates')

@chan_blueprint.route('/')
def home():
    boards = Board.query.all()
    return render_template('chan/home.html', boards=boards)


@chan_blueprint.route('/board/<id>', methods=['POST', 'GET'])
def board(id):
    form = PostForm()
    board = Board.query.get(id)

    if form.validate_on_submit():
        if current_user.is_authenticated:
            user_id = current_user.id
            auth = current_user.name
            new_post = Posts(auth=auth, content=form.text.data, board_id=board.id, user_id=user_id)
        else:
            new_post = Posts(auth=form.name.data, content=form.text.data, board_id=board.id, user_id=None)
        # new_post = Posts(auth=form.name.data, content=form.text.data, board_id=board.id, user_id=user_id)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('chan.board', id=board.id))
    return render_template('chan/board.html', board=board, form=form)

meine/users/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, flash
from meine.users.forms import LoginForm, BoardForm, DelPost, ChangePass
from meine.models import Users, Board, db, Posts
from flask_login import login_user, login_required, logout_user, current_user

users_blueprint = Blueprint('users', __name__, template_folder='templates')

def edit_comment(post, new_content):
    if post.date_edit == None:
        post.edit_date = post.set_edit_date()
        db.session.add(post)
        db.session.commit()

    signature = f"\n\n\nPost edytowany: {post.show_edit_date()} przez {current_user.name}"
    post.content = str(new_content) + str(signature)
    db.session.add(post)
    db.session.commit()

def board_list():
    default = (0, 'Nic nie usuwaj')
    choice = [default]
    for board in Board.query.all():
        choice.append((board.id, board.name))

    return choice

@users_blueprint.route('/', methods=['POST', 'GET'])
def home():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(name=form.name.data).first()
        if not user:
            flash('Nie ma takiego użytkownika')
        else:
            if user.check_password(form.password.data):
                login_user(user)
                return redirect(url_for('home'))
            else:
                flash('Złe hasło')



    return render_template('users/home.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

@users_blueprint.route('/admin')
@login_required
def admin():
    if current_user.role > 1:
        return redirect(url_for('home'))

    return render_template('users/admin.html')

@users_blueprint.route('/admin/board', methods=['POST', 'GET'])
@login_required
def add_board():
    form = BoardForm()
    if form.validate_on_submit():
        new_board = Board(name=form.name.data, info=form.info.data)
        db.session.add(new_board)
        db.session.commit()

        return redirect(url_for('chan.home'))

    return render_template('users/add_board.html', form=form)

@users_blueprint.route('/admin/delete', methods=['POST', 'GET'])
@login_required
def del_board():
    boards = Board.query.all()

    if request.method == 'POST':
        if request.form['boardRadio'] == '0':
            return redirect(url_for('users.admin'))
        deleted = Board.query.get(request.form['boardRadio'])
        db.session.delete(deleted)
        db.session.commit()

        return redirect(url_for('users.del_board'))



    return render_template('users/del_board.html', boards=boards)


@users_blueprint.route('/edit/<id>', methods=['POST', 'GET'])
@login_required
def edit_post(id):
    edited = Posts.query.get(id)
    if request.method == 'POST':
        new = request.form['editedPost']
        edit_comment(edited, new)

        return redirect(url_for('chan.board', id=edited.board_id))



    return render_template('users/edit_post.html', edited=edited)

@users_blueprint.route('/del/<id>', methods=['POST', 'GET'])
@login_required
def del_post(id):
    deleted = Posts.query.get(id)
    del_post = DelPost()
    if del_post.validate_on_submit():
        db.session.delete(deleted)
        db.session.commit()
        return redirect(url_for('chan.board', id=deleted.board_id))
    return render_template('users/del_post.html', deleted=deleted, form=del_post)

@users_blueprint.route('admin/account', methods=['POST', 'GET'])
@login_required
def change_pass():
    form = ChangePass()
    c_user = Users.query.get(current_user.id)

    if form.validate_on_submit():
        if not c_user.check_password(form.old_pass.data):
            flash('Stare hasło jest niepoprawne')
        else:

            print(form.confirm_pass.errors)
            c_user.set_password(form.confirm_pass.data)
            db.session.add(c_user)
            db.session.commit()
            flash('Ustawiono nowe hasło')


    return render_template('users/change_pass.html', form=form)

@users_blueprint.route('admin/move/<id>', methods=['POST', 'GET'])
@login_required
def move_post(id):
    moved = Posts.query.get(id)
    boards = Board.query.all()
    if request.method == 'POST':
        if request.form['boardRadio'] == '0':
            return redirect(url_for('chan.board', id=moved.board_id))
        target = Board.query.get(request.form['boardRadio'])
        moved.board_id = target.id
        db.session.add(moved)
        db.session.commit()
        flash('Post został przeniesiony')
        return redirect(url_for('chan.board', id=moved.board_id))

    return render_template('users/move_post.html', moved=moved, boards=boards)

meine/templates/_macros.html
{% macro show_Board(board_id) %}

<div class="container my-3 border border-dark">
            <div class="row shadow mb-5 bg-body bg-rounded">

                <div class="col-12 text-center bg-primary bg-opacity-50">
                    <a class="link-dark" href="{{ url_for('chan.board', id=board_id.id) }}"> <h2> {{ board_id.name }} </h2> </a>
                </div>

                <div class="col-md-4 bg-danger p-1">
                    <a href="{{ url_for('chan.board', id=board_id.id) }}"> <img src="{{ url_for('static', filename='img/thumb2.png') }}" class="rounded mx-auto d-block" style="height: 100px;"> </a>
                </div>

                <div class="col-md-8 bg-light p-2">
                    <p style="white-space: pre-wrap;"> {{ board_id.info }} </p>
                    <p class="text-end fst-italic"> Tablicę utworzono: {{ board_id.show_date() }} </p>
                </div>


            </div>
</div>

{% endmacro %}




{% macro show_Post(post) %}


    <div class="container my-2 bg-white bg-opacity-50 border border-secondary">
    
            
                {% if post.check_owner() %}

         <div class="row bg-warning bg-opacity-50">        
            <div class="col-6">    
                    <p class="text-center text-danger fst-italic fs-5"> {{ post.auth }} </p>

                {% else %}
        <div class="row">        
            <div class="col-6">
                    <p class="text-center fst-italic fs-5"> {{ post.auth }} </p>
                
                {% endif %}
 
            </div>
            <div class="col-6">
                <p class="text-end"> {{ post.show_date() }}</p>
            </div>
        </div>

        <div class="row border-bottom border-success justify-content-center">
            
            <div class="col-10 col-md-8">
                <p class="text-center" style="white-space: pre-wrap;"> {{ post.content }} </p>
            </div>
        </div>
        {% if current_user.is_authenticated %}
            <div class="row">
                <div class="col-md-4 col-6 text-center bg-danger bg-opacity-25 my-2"> 
                    <a href="{{ url_for('users.edit_post', id=post.id) }}" class="btn btn-danger"> Edytuj Post </a>
                </div>

                <div class="col-md-4 col-6 text-center bg-danger bg-opacity-25 my-2"> 
                    <a href="{{ url_for('users.del_post', id=post.id) }}" class="btn btn-danger"> Usuń Post !!! </a>
                </div>

                <div class="col-md-4 col-6 text-center bg-danger bg-opacity-25 my-2"> 
                    <a href="{{ url_for('users.move_post', id=post.id) }}" class="btn btn-danger"> Przenieś </a>
                </div>
            </div>
        {% endif %}
    </div>
    
{% endmacro %}







{% macro radio_Board(boards, text) %}

    <div class="form-check">

        <input class="form-check-input" type="radio" name="boardRadio" value="0" id="radioBoard0" checked>
        <label class="form-check-label fs-3" for="radioBoard0"> {{ text }} </label>
    </div>

    {% for board in boards %}

        <div class="form-check">

        <input class="form-check-input" type="radio" name="boardRadio" value="{{ board.id }}" id="radioBoard{{board.id}}">
        <label class="form-check-label fs-3" for="radioBoard{{board.id}}"> {{ board.name }} </label>
        </div>


    {% endfor %}
    
    
{% endmacro %}

meine/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
    <title>Chan Machen</title>
</head>
<body style="
        background-image: url( {{ url_for('static', filename='img/tlo04.jpeg') }} );
        background-position: top center;
        background-repeat: repeat;">

    <div class="container">


        <div class="container d-flex align-items-center justify-content-center" style="
                    height: 140px;
                    background-image: url( {{ url_for('static', filename='img/tlo03.jpeg') }} );
                    background-position: top center;
                    ">
            <h1> RockChan </h1>
        </div>


        <header>

            <div class="nav-bar bg-info">
                <a class="navbar-brand" href="{{ url_for('home') }}"> <img src="{{ url_for('static', filename='img/home2.png') }}" width="40" height="40" class="d-inline-block mx-1">Home </a>
                <a class="navbar-brand mx-2" href="{{ url_for('chan.home') }}"> <img src="{{ url_for('static', filename='img/blog4.jpg') }}" width="40" height="40" class="d-inline-block mx-1">Chan </a>
                {% if current_user.is_authenticated %}
                    <a class="navbar-brand" href="{{ url_for('users.logout') }}"> <img src="{{ url_for('static', filename='img/home2.png') }}" width="40" height="40" class="d-inline-block mx-1">Wyloguj </a>
                    <a class="navbar-brand" href="{{ url_for('users.admin') }}"> <img src="{{ url_for('static', filename='img/home2.png') }}" width="40" height="40" class="d-inline-block mx-1">Admin </a>
                {% else %}
                     <a class="navbar-brand mx-2" href="{{ url_for('users.home') }}"> <img src="{{ url_for('static', filename='img/blog4.jpg') }}" width="40" height="40" class="d-inline-block mx-1">Users </a>
                {% endif %}
               
            </div>




        </header>


        <content>
            {% block content %}
            {% endblock %}
        </content>















    </div>









<script src="{{ url_for('static', filename='bootstrap.bundle.js') }}"></script>
</body>
</html>

meine/templates/home.html
{% extends "base.html" %}

{% block content %}
	<div class="container my-3 main-width bg-white bg-opacity-50">
		<div class="row text-center">
			<h2> Witaj na RockChanie </h2>
		</div>
		<p> Chan służy wymianie informacji o naszym zakładzie pracy, wspólnej rozmowie na różne tematy. </p>
		<div class="row my-3 d-flex justify-content-center">
			<div class="col-12 my-1 text-center">
				<h5> Kliknij na Kłębek Wełny aby Wejść !!! </h3>
			</div>
			<div class="col12 my-1 d-flex justify-content-center">
				<a href="{{ url_for('chan.home') }}">
					<img src="{{ url_for('static', filename='img/wool3.jpg') }}" class="rounded mx-auto d-block" alt="kłebek wełny" style="max-width: 400px; max-height: 400px;">
				</a>
			</div>
		</div>
	</div>

{% endblock %}

meine/templates/no_enter.html
{% extends "base.html" %}

{% block content %}
	<div class="container my-3 bg-white bg-opacity-50 main-width">
		<div class="row text-center">
			<h3> Nie masz uprawnień do przeglądania tej strony </h3>
			<h4> Nic nie rób zostaniesz przekierowany na stronę główną </h4>

		</div>

		<div class="container d-flex justify-content-center" style="max-width: 700px;">
			
			<img src="{{ url_for('static', filename='img/lock03.jpg') }}" class="rounded mx-auto d-block" alt="brak dostępu" style="max-width: 400px; max-height: 400px;">


			
		</div>
	</div>


	<script>
		window.setTimeout(function()
		{
			window.location.href = "{{ url_for('home') }}";
		}, 5000);
	</script>

{% endblock %}